//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityTrial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_USER
    {
        public SYSTEM_USER()
        {
            this.SYSTEM_USER_CLAIM = new HashSet<SYSTEM_USER_CLAIM>();
            this.SYSTEM_USER_LOGIN = new HashSet<SYSTEM_USER_LOGIN>();
            this.SYSTEM_USER_ROLE = new HashSet<SYSTEM_USER_ROLE>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NT_UserName { get; set; }
        public Nullable<bool> NT_Logon { get; set; }
        public Nullable<bool> ExpirePassword { get; set; }
        public Nullable<System.DateTime> PasswordExpiryDate { get; set; }
        public string Email { get; set; }
        public string EmailHash { get; set; }
        public string PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChangedDate { get; set; }
        public Nullable<System.DateTime> LastLockoutDate { get; set; }
        public Nullable<int> FailedPasswordAttemptCount { get; set; }
        public Nullable<System.DateTime> FailedPasswordAttemptWindowStart { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> RegionID { get; set; }
        public Nullable<decimal> LanguageID { get; set; }
        public string DecimalSeperator { get; set; }
        public string DateFormat { get; set; }
        public string Discriminator { get; set; }
        public string SecurityStamp { get; set; }
    
        public virtual ICollection<SYSTEM_USER_CLAIM> SYSTEM_USER_CLAIM { get; set; }
        public virtual ICollection<SYSTEM_USER_LOGIN> SYSTEM_USER_LOGIN { get; set; }
        public virtual ICollection<SYSTEM_USER_ROLE> SYSTEM_USER_ROLE { get; set; }
    }
}
