//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityTrial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_USER_CLAIM
    {
        public string UserId { get; set; }
        //public int Id { get; set; }
        //public string ClaimType { get; set; }
        //public string ClaimValue { get; set; }
    
        public virtual SYSTEM_USER SYSTEM_USER { get; set; }
    }
}
