//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityTrial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_USER_ROLE
    {
        override public string UserId { get; set; }
        override public string RoleId { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string Discriminator { get; set; }
    
        public virtual SYSTEM_ROLE SYSTEM_ROLE { get; set; }
        public virtual SYSTEM_USER SYSTEM_USER { get; set; }
    }
}
